### ISSUE TITLE
Document category links should be in md files and replace loopback HTML in .md files with processing in the theme

### ISSUE THREAD

**Issue by stevector** [stevector/wordpress-at-scale#9]

**Comment by joshkoenig** [comment]
I'm ok with some amount of header/footer formatting in the files, especailly if we can contextualize with a comment.

**Comment by stevector** [comment]
OK, I'd at least like to remove the loopback header and footer from the md files since the logic is as simple as "print this link to the previous page in the menu" and "print this link/image for the next page in the menu". And in coding those elements into the theme I found that even the manual entries were messing up some of the background images on those 'next' page footers.

I'm going to turn this issue into an implementation task and remove the live-env-blocker tag as I think the work of replacing the loopback links is best done after getting the syncing working at all. Part of my reason for that is because I want to use wraith for testing deployments of the rest of the work and this change will fix background images (which will cause wraith failures).

**Comment by stevector** [comment]
I'm taking out the loop links now.
